# Generated by Django 6.0.4 on 2026-04-28 06:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data', 'Data & Analytics'), ('devops', 'DevOps & Infrastructure'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('other', 'Other')], default='other', help_text='Danh mục của dự án.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='KEY', help_text='Mã định danh ngắn của dự án (VD: PROJ, MY-APP). Chỉ A–Z, 0–9, dấu "-", 2–10 ký tự.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Project key chỉ được chứa chữ hoa (A–Z), số (0–9) và dấu gạch ngang (-). Độ dài từ 2 đến 10 ký tự và phải bắt đầu bằng chữ hoa hoặc số.', regex='^[A-Z0-9][A-Z0-9\\-]{1,9}$')]),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('software', 'Software'), ('business', 'Business'), ('service', 'Service')], default='software', help_text='Loại dự án: software, business hoặc service.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['key'], name='idx_project_key'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='idx_project_type'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='idx_project_category'),
        ),
    ]
